export { Header } from './header/header'
export { Footer } from './footer/footer'
export { StaticPagePlaceholder } from './static-page/static-page-placeholder'
export { Container } from './container'
export { CookieConsentBanner } from './cookie-consent/cookie-consent-banner'
